#!/bin/bash

if [ -f ~/.bashrc ];
then
	rm ~/.bashrc
fi
if [ -f ~/.gitconfig ];
then
	rm ~/.gitconfig
fi
if [ -f ~/.tmux.conf ];
then
	rm ~/.tmux.conf
fi
ln -s ~/config/.bashrc ~/.bashrc
ln -s ~/config/.gitconfig ~/.gitconfig
ln -s ~/config/.tmux.conf ~/.tmux.conf

